;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        clean-aindent--bsunindent
        helm-M-x
        indent-for-tab-command
        paredit-close-round
        paredit-forward-barf-sexp
        paredit-kill
        paredit-open-round
        paredit-semicolon
        prelude-move-beginning-of-line
        slime-autodoc-space
        undo-tree-visualize
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        exwm-workspace-switch
        org-self-insert-command
        sgml-attributes
        ))
